In [1]:
from google.cloud import storage

In [2]:



def list_keys(project_id):
    """
    List all HMAC keys associated with the project.
    """
    # project_id = "Your Google Cloud project ID"

    storage_client = storage.Client(project=project_id)
    hmac_keys = storage_client.list_hmac_keys(project_id=project_id)
    print("HMAC Keys:")
    for hmac_key in hmac_keys:
        print(
            "Service Account Email: {}".format(hmac_key.service_account_email)
        )
        print("Access ID: {}".format(hmac_key.access_id))
    return hmac_keys

In [3]:


def activate_key(access_id, project_id):
    """
    Activate the HMAC key with the given access ID.
    """
    # project_id = "Your Google Cloud project ID"
    # access_id = "ID of an inactive HMAC key"

    storage_client = storage.Client(project=project_id)

    hmac_key = storage_client.get_hmac_key_metadata(
        access_id, project_id=project_id
    )
    hmac_key.state = "ACTIVE"
    hmac_key.update()

    print("The HMAC key metadata is:")
    print("Service Account Email: {}".format(hmac_key.service_account_email))
    print("Key ID: {}".format(hmac_key.id))
    print("Access ID: {}".format(hmac_key.access_id))
    print("Project ID: {}".format(hmac_key.project))
    print("State: {}".format(hmac_key.state))
    print("Created At: {}".format(hmac_key.time_created))
    print("Updated At: {}".format(hmac_key.updated))
    print("Etag: {}".format(hmac_key.etag))
    return hmac_key

In [4]:
def download_blob(bucket_name, source_blob_name, destination_file_name):
    """Downloads a blob from the bucket."""
    # bucket_name = "your-bucket-name"
    # source_blob_name = "storage-object-name"
    # destination_file_name = "local/path/to/file"

    storage_client = storage.Client()

    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    blob.download_to_filename(destination_file_name)

    return

In [20]:
bucket_name = 'robostock'
source_blob_name = 'AllCompanies_October.csv'

In [14]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '/Users/murtazavahanvaty/Downloads/ted-lvgsks-03bf07238b8c.json'

In [21]:
storage_client = storage.Client()

bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(source_blob_name)

In [ ]:
type(blob)

In [ ]:
pd.Timestamp.now().month_name()

In [22]:
data = blob.download_as_string()
df = pd.read_csv(io.BytesIO(data))

In [17]:
import pandas as pd
import io

In [23]:
df

,Unnamed: 0,symbol,name,price,income_statement_date,ROC,EarningsYield,irr,npv_mean,npv_regression,...,QA,MCap,PE,eps_roc_flag,eps_base,eps_list,error_message,ROC_rank,EarningsYield_rank,Total_rank
0,2,BYND,"Beyond Meat, Inc.",100.58,2020-12-31,-0.115014,-0.006629,NaN,-8.403080,-17.384928,...,2.366147,6.433605e+09,-70.333891,Negative,-1.247836,"[-0.64, -0.29, -1.2478362688938607]",NaN,3,3,6
1,1,AMAT,"Applied Materials, Inc.",126.22,2020-10-25,0.405443,0.036260,0.079722,25.789187,119.363710,...,2.122673,1.151235e+11,21.814585,Negative,3.829630,"[2.96101, 2.86349, 3.8296296296296295]",NaN,2,1,3
2,0,AAPL,Apple Inc.,142.90,2020-09-26,0.882816,0.026803,-0.108430,35.911485,38.593723,...,1.325072,2.360678e+12,27.359283,Negative,3.310000,"[3.0025, 2.9925, 3.31]",NaN,1,2,3

In [25]:
def get_data_from_cloud(filename):
    source_blob_name = filename
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    data = blob.download_as_string()
    irr_df = pd.read_csv(io.BytesIO(data))
    return irr_df

In [26]:
get_data_from_cloud(filename='AllCompanies_October.csv')

,Unnamed: 0,symbol,name,price,income_statement_date,ROC,EarningsYield,irr,npv_mean,npv_regression,...,QA,MCap,PE,eps_roc_flag,eps_base,eps_list,error_message,ROC_rank,EarningsYield_rank,Total_rank
0,2,BYND,"Beyond Meat, Inc.",100.58,2020-12-31,-0.115014,-0.006629,NaN,-8.403080,-17.384928,...,2.366147,6.433605e+09,-70.333891,Negative,-1.247836,"[-0.64, -0.29, -1.2478362688938607]",NaN,3,3,6
1,1,AMAT,"Applied Materials, Inc.",126.22,2020-10-25,0.405443,0.036260,0.079722,25.789187,119.363710,...,2.122673,1.151235e+11,21.814585,Negative,3.829630,"[2.96101, 2.86349, 3.8296296296296295]",NaN,2,1,3
2,0,AAPL,Apple Inc.,142.90,2020-09-26,0.882816,0.026803,-0.108430,35.911485,38.593723,...,1.325072,2.360678e+12,27.359283,Negative,3.310000,"[3.0025, 2.9925, 3.31]",NaN,1,2,3